# Generated by Django 4.1.13 on 2024-07-10 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to="django-import-jobs/",
                        verbose_name="File to be imported",
                    ),
                ),
                (
                    "processing_initiated",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Started processing the file",
                    ),
                ),
                (
                    "imported",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Import completed",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        max_length=255, verbose_name="Format of file to be imported"
                    ),
                ),
                (
                    "change_summary",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="django-import-job-change-summaries/",
                        verbose_name="Summary of changes made by this import",
                    ),
                ),
                (
                    "errors",
                    models.TextField(blank=True, default="", verbose_name="Errors"),
                ),
                (
                    "model",
                    models.CharField(
                        max_length=160, verbose_name="Name of model to import to"
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Status of the job"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Import job",
                "verbose_name_plural": "Import jobs",
            },
        ),
    ]
