# Generated by Django 5.1.2 on 2024-11-12 18:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "import_export_job",
            "0003_alter_importjob_change_summary_alter_importjob_file",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importjob",
            name="owner",
        ),
        migrations.AddField(
            model_name="importjob",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2024, 11, 12, 0, 0)
            ),
            preserve_default=False,
        ),
    ]
