receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: http://jaeger:4317
    tls:
      insecure: true

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 180
    spike_limit_mib: 30

  batch:
    timeout: 1s
    send_batch_size: 256
    send_batch_max_size: 512

  probabilistic_sampler:
    sampling_percentage: 100

service:
  telemetry:
    logs:
      level: INFO
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters:
        - debug
    traces:
      receivers: [otlp]
      processors: [memory_limiter, probabilistic_sampler, batch]
      exporters:
        - debug
        - otlp/jaeger
