receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: http://jaeger:4317
    tls:
      insecure: true

processors:
  batch:

service:
  telemetry:
    logs:
      level: DEBUG
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - debug
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - debug
        - otlp/jaeger
