# Generated by Django 4.2.3 on 2023-07-21 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("referentie_tabellen", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spatialdimensiontype",
            old_name="type",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="temporaldimensiontype",
            old_name="type",
            new_name="name",
        ),
    ]
