# Generated by Django 5.2.4 on 2025-11-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referentie_tabellen", "0003_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporaldimensiontype",
            name="type",
            field=models.IntegerField(
                choices=[(1, "Peildatum"), (2, "Periode")], default=2
            ),
        ),
    ]
