# Generated by Django 6.0.2 on 2026-02-27 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("referentie_tabellen", "0005_alter_theme_group"),
        ("statistiek_hub", "0016_update_measure_team_from_referentie_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="group",
        ),
    ]
