# Generated by Django 4.1.2 on 2023-02-07 16:21

from django.db import migrations

from publicatie_tabellen.db_functions.function_apply_filter import function_apply_filter
from publicatie_tabellen.db_functions.function_calculate_observations import (
    function_calculate_observation,
)
from publicatie_tabellen.db_functions.function_publish_measures import (
    function_publish_measures,
)
from publicatie_tabellen.db_functions.function_publish_observations import (
    function_publish_observations,
)
from publicatie_tabellen.db_functions.function_publish_statistics import (
    function_publish_statistics,
)
from publicatie_tabellen.db_functions.function_round_observation import (
    function_round_observation,
)


class Migration(migrations.Migration):
    dependencies = [
        ("publicatie_tabellen", "0001_initial"),
        ("statistiek_hub", "0001_initial"),     
    ]

    operations = [
        migrations.RunSQL(function_calculate_observation),
        migrations.RunSQL(function_round_observation),
        migrations.RunSQL(function_apply_filter),
        migrations.RunSQL(function_publish_measures),
        migrations.RunSQL(function_publish_observations),
        migrations.RunSQL(function_publish_statistics),
    ]
