# Generated by Django 5.1.2 on 2024-11-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publicatie_tabellen", "0002_db_functions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationUpdatedAt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
