# Generated by Django 4.1.13 on 2024-03-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicatie_tabellen", "0002_db_functions"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationstatistic",
            name="temporaldimensionyear",
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicationmeasure",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="publicationobservation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="publicationobservation",
            name="temporaldimensionenddate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="publicationobservation",
            name="temporaldimensionstartdate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="publicationstatistic",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="publicationstatistic",
            name="temporaldimensionstartdate",
            field=models.DateField(),
        ),
    ]
