# Generated by Django 4.1.13 on 2024-05-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "publicatie_tabellen",
            "0003_publicationobservation_temporaldimensionyear_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationstatistic",
            name="average",
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
        migrations.AlterField(
            model_name="publicationstatistic",
            name="standarddeviation",
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
    ]
