# Generated by Django 5.1.5 on 2025-03-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publicatie_tabellen", "0005_log_table_model_changes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangesLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=255, unique=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "changes_log",
                "managed": False,
            },
        ),
    ]
