# Generated by Django 5.2.2 on 2025-07-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicatie_tabellen', '0006_changeslog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publicationobservation',
            index=models.Index(models.F('measure'), name='measure_idx'),
        ),
    ]
