# Generated by Django 6.0.3 on 2026-05-13 12:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publicatie_tabellen", "0009_publicationmeasure_description_uk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationmeasure",
            name="source",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="publicationmeasure",
            name="theme",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list),
        ),
        migrations.AlterField(
            model_name="publicationmeasure",
            name="theme_uk",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list),
        ),
    ]
