# Generated by Django 4.1.7 on 2023-06-20 13:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referentie_tabellen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dimension",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("version", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "dimension",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Measure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=75)),
                ("label_uk", models.CharField(blank=True, max_length=75, null=True)),
                ("definition", models.TextField()),
                ("definition_uk", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "calculation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("decimals", models.IntegerField(default=0)),
                ("source", models.CharField(max_length=100)),
                (
                    "extra_attr",
                    models.JSONField(
                        blank=True, help_text="jsonfield voor productvelden", null=True
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(default=False, help_text="vervallen"),
                ),
                ("deprecated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "deprecated_reason",
                    models.TextField(blank=True, help_text="toelichting", null=True),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="statistiek_hub.dimension",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="statistiek_hub.measure",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="referentie_tabellen.theme",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="referentie_tabellen.unit",
                    ),
                ),
            ],
            options={
                "db_table": "measure",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("version", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "topic",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TemporalDimension",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("startdate", models.DateTimeField()),
                ("enddate", models.DateTimeField()),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="statistiek_hub.temporaldimension",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="referentie_tabellen.temporaldimensiontype",
                    ),
                ),
            ],
            options={
                "db_table": "temporaldimension",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SpatialDimension",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("code", models.CharField(max_length=100)),
                ("source_id", models.CharField(blank=True, max_length=100, null=True)),
                ("source_date", models.DateField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=28992
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="statistiek_hub.spatialdimension",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="referentie_tabellen.spatialdimensiontype",
                    ),
                ),
            ],
            options={
                "db_table": "spatialdimension",
                "managed": True,
                "unique_together": {("code", "type", "source_date")},
            },
        ),
        migrations.CreateModel(
            name="Filter",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rule", models.TextField()),
                ("value_new", models.FloatField(blank=True, null=True)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistiek_hub.measure",
                    ),
                ),
            ],
            options={
                "db_table": "filter",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DimensionGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dimensionkey", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("version", models.CharField(max_length=15)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="statistiek_hub.dimensiongroup",
                    ),
                ),
            ],
            options={
                "db_table": "dimensiongroup",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="dimension",
            name="dimensiongroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="statistiek_hub.dimensiongroup",
            ),
        ),
        migrations.AddField(
            model_name="dimension",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="statistiek_hub.dimension",
            ),
        ),
        migrations.CreateModel(
            name="TopicSet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistiek_hub.measure",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistiek_hub.topic",
                    ),
                ),
            ],
            options={
                "db_table": "topicset",
                "managed": True,
                "unique_together": {("topic", "measure")},
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.FloatField()),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistiek_hub.measure",
                    ),
                ),
                (
                    "spatialdimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="statistiek_hub.spatialdimension",
                    ),
                ),
                (
                    "temporaldimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="statistiek_hub.temporaldimension",
                    ),
                ),
            ],
            options={
                "db_table": "observation",
                "managed": True,
                "unique_together": {
                    ("measure", "spatialdimension", "temporaldimension")
                },
            },
        ),
    ]
