# Generated by Django 4.1.13 on 2024-03-08 14:18

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referentie_tabellen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dimension",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("version", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Measure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=75)),
                ("label_uk", models.CharField(blank=True, max_length=75, null=True)),
                ("definition", models.TextField()),
                ("definition_uk", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "calculation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="gevoeligedata - afronden en groepsonthulling toepassen",
                    ),
                ),
                ("decimals", models.IntegerField(default=0)),
                ("source", models.CharField(max_length=100)),
                (
                    "extra_attr",
                    models.JSONField(
                        blank=True, help_text="jsonfield voor productvelden", null=True
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(default=False, help_text="vervallen"),
                ),
                ("deprecated_date", models.DateField(blank=True, null=True)),
                (
                    "deprecated_reason",
                    models.TextField(blank=True, help_text="toelichting", null=True),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="statistiek_hub.dimension",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="statistiek_hub.measure",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="referentie_tabellen.theme",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="referentie_tabellen.unit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("version", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="TopicSet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistiek_hub.measure",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistiek_hub.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemporalDimension",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(editable=False, max_length=50)),
                ("startdate", models.DateField()),
                ("enddate", models.DateField(editable=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="statistiek_hub.temporaldimension",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="referentie_tabellen.temporaldimensiontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpatialDimension",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(max_length=100)),
                ("source_id", models.CharField(blank=True, max_length=100, null=True)),
                ("source_date", models.DateField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=28992
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="statistiek_hub.spatialdimension",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="referentie_tabellen.spatialdimensiontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.FloatField()),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistiek_hub.measure",
                    ),
                ),
                (
                    "spatialdimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="statistiek_hub.spatialdimension",
                    ),
                ),
                (
                    "temporaldimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="statistiek_hub.temporaldimension",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Filter",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rule", models.TextField()),
                ("value_new", models.FloatField(blank=True, null=True)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="statistiek_hub.measure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DimensionGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dimensionkey", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("version", models.CharField(max_length=15)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="statistiek_hub.dimensiongroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dimension",
            name="dimensiongroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="statistiek_hub.dimensiongroup",
            ),
        ),
        migrations.AddField(
            model_name="dimension",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="statistiek_hub.dimension",
            ),
        ),
        migrations.AddIndex(
            model_name="temporaldimension",
            index=models.Index(
                models.F("type"),
                models.F("startdate"),
                name="unique_temporaldimension_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spatialdimension",
            index=models.Index(
                models.F("code"),
                models.F("type"),
                models.F("source_date"),
                name="unique_spatialdimension_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                models.F("measure"),
                models.F("spatialdimension"),
                models.F("temporaldimension"),
                name="unique_observation_idx",
            ),
        ),
    ]
