# Generated by Django 4.1.13 on 2024-03-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistiek_hub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporaldimension",
            name="year",
            field=models.PositiveIntegerField(default=2024, editable=False),
            preserve_default=False,
        ),
    ]
