# Generated by Django 4.1.13 on 2024-03-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("statistiek_hub", "0002_temporaldimension_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obs_measure",
                to="statistiek_hub.measure",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="spatialdimension",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="obs_spatialdimension",
                to="statistiek_hub.spatialdimension",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="temporaldimension",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="obs_temporaldimension",
                to="statistiek_hub.temporaldimension",
            ),
        ),
        migrations.CreateModel(
            name="ObservationCalculated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.FloatField()),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calc_obs_measure",
                        to="statistiek_hub.measure",
                    ),
                ),
                (
                    "spatialdimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="calc_obs_spatialdimension",
                        to="statistiek_hub.spatialdimension",
                    ),
                ),
                (
                    "temporaldimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="calc_obs_temporaldimension",
                        to="statistiek_hub.temporaldimension",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="observationcalculated",
            index=models.Index(
                models.F("measure"),
                models.F("spatialdimension"),
                models.F("temporaldimension"),
                name="unique_calc_observation_idx",
            ),
        ),
    ]
