# Generated by Django 4.1.13 on 2024-04-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "statistiek_hub",
            "0003_alter_observation_id_alter_observation_measure_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="temporaldimension",
            constraint=models.UniqueConstraint(
                fields=("type", "startdate"), name="duplicate_tempdim_constraint"
            ),
        ),
    ]
