# Generated by Django 4.1.12 on 2023-11-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistiek_hub", "0004_alter_temporaldimension_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="sensitive",
            field=models.BooleanField(
                default=False,
                help_text="gevoeligedata - afronden en groepsonthulling toepassen",
            ),
        ),
        migrations.AlterField(
            model_name="spatialdimension",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
