# Generated by Django 4.1.13 on 2024-05-10 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "statistiek_hub",
            "0005_observation_duplicate_observation_constraint_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observationcalculated",
            options={"verbose_name_plural": "observations calculated"},
        ),
    ]
