# Generated by Django 4.1.13 on 2024-05-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistiek_hub", "0006_alter_observationcalculated_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="calculation",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="measure",
            name="definition_uk",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="measure",
            name="deprecated_reason",
            field=models.TextField(blank=True, default="", help_text="toelichting"),
        ),
        migrations.AlterField(
            model_name="measure",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="measure",
            name="label_uk",
            field=models.CharField(blank=True, default="", max_length=75),
        ),
    ]
