# Generated by Django 4.1.13 on 2024-05-31 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistiek_hub", "0007_alter_measure_calculation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter",
            name="measure",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="statistiek_hub.measure"
            ),
        ),
    ]
