# Generated by Django 4.1.13 on 2024-06-21 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistiek_hub", "0008_alter_filter_measure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filter",
            name="id",
        ),
        migrations.AlterField(
            model_name="filter",
            name="measure",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="statistiek_hub.measure",
            ),
        ),
    ]
