# Generated by Django 4.1.7 on 2023-07-21 12:22

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistiek_hub", "0003_create_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="deprecated_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporaldimension",
            name="enddate",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="temporaldimension",
            name="startdate",
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
    ]
