# Generated by Django 4.2.3 on 2023-07-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistiek_hub", "0009_alter_measure_deprecated_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporaldimension",
            name="name",
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AddConstraint(
            model_name="temporaldimension",
            constraint=models.UniqueConstraint(
                fields=("type", "startdate"), name="unique_temporaldim"
            ),
        ),
    ]
