# Generated by Django 5.1.4 on 2025-02-07 11:39

from django.db import migrations, models

import statistiek_hub.validations


class Migration(migrations.Migration):
    dependencies = [
        ("statistiek_hub", "0011_alter_filter_rule_alter_measure_calculation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="calculation",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                validators=[statistiek_hub.validations.validate_calculation_string],
            ),
        ),
    ]
