# Generated by Django 4.1.2 on 2023-02-07 16:39

from django.db import migrations

from statistiek_hub.view_tabellen.view_calculated_observation import (
    vw_calculated_observation,
)
from statistiek_hub.view_tabellen.view_publish_measure import vw_publish_measure
from statistiek_hub.view_tabellen.view_publish_observation import vw_publish_observation
from statistiek_hub.view_tabellen.view_publish_product import vw_publish_product


class Migration(migrations.Migration):
    dependencies = [
        ("statistiek_hub", "0005_measure_sensitive_alter_spatialdimension_name"),
    ]

    operations = [
        migrations.RunSQL(
            vw_calculated_observation["query"], vw_calculated_observation["reverse"]
        ),
        migrations.RunSQL(vw_publish_measure["query"], vw_publish_measure["reverse"]),
        migrations.RunSQL(
            vw_publish_observation["query"], vw_publish_observation["reverse"]
        ),
        migrations.RunSQL(vw_publish_product["query"], vw_publish_product["reverse"]),
    ]
