# Generated by Django 5.1.5 on 2025-03-25 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistiek_hub", "0012_alter_measure_calculation"),
    ]

    operations = [
        migrations.AddField(
            model_name="filter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
