# Generated by Django 5.2.4 on 2025-11-07 11:25

from django.db import migrations, models

import statistiek_hub.validations


class Migration(migrations.Migration):
    dependencies = [
        ("statistiek_hub", "0013_filter_created_at_filter_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="temporaltype",
            field=models.IntegerField(choices=[(1, "Peildatum"), (2, "Periode")], default=1),
        ),
        migrations.AlterField(
            model_name="measure",
            name="calculation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="sql berekeningsregel, alleen invullen voor een berekende variabele",
                max_length=200,
                validators=[statistiek_hub.validations.validate_calculation_string],
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="sensitive",
            field=models.BooleanField(
                default=False,
                help_text="gevoeligedata - afronden op veelvouden van 5 of 90% en gebieden met minder dan 50 inwoners worden leeg gemaakt",
            ),
        ),
    ]
