# Generated by Django 6.0.2 on 2026-02-27 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("statistiek_hub", "0016_update_measure_team_from_referentie_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="team",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("name__startswith", "modifier_"),
                    ("name__startswith", "maintainer"),
                    _connector="OR",
                    _negated=True,
                ),
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="auth.group",
            ),
        ),
    ]
