# Generated by Django 6.0.2 on 2026-03-03 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("statistiek_hub", "0017_alter_measure_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="team",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("name__startswith", "modifier_"),
                    ("name__startswith", "maintainer"),
                    _connector="OR",
                    _negated=True,
                ),
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="auth.group",
            ),
        ),
    ]
