# Generated by Django 6.0.2 on 2026-03-10 15:44

from django.db import migrations

def migrate_foreignkey_to_manytomany(apps, schema_editor):
    Measure = apps.get_model('statistiek_hub', 'Measure')
    for measure in Measure.objects.all():
        if measure.theme:  # Check if the ForeignKey field has a value
            measure.themes.add(measure.theme)  # Add the ForeignKey value to the ManyToManyField

class Migration(migrations.Migration):

    dependencies = [
        ('statistiek_hub', '0019_measure_themes'),
    ]

    operations = [
        migrations.RunPython(migrate_foreignkey_to_manytomany),
    ]
