# Generated by Django 6.0.2 on 2026-03-10 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("statistiek_hub", "0020_auto_20260310_1544"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="theme",
        ),
    ]
