# Generated by Django 6.0.3 on 2026-05-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referentie_tabellen", "0006_remove_theme_group"),
        ("statistiek_hub", "0023_measure_fill_new_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measure",
            old_name="source",
            new_name="source_old",
        ),
        migrations.AddField(
            model_name="measure",
            name="sources",
            field=models.ManyToManyField(related_name="measures_sources", to="referentie_tabellen.source"),
        ),
    ]
