# Generated by Django 6.0.3 on 2026-06-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistiek_hub', '0024_rename_source_measure_source_old_measure_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='source_old',
        ),
    ]
