name: Opdrachten Team Dependabot

on:
  schedule: # Run the script on the 1st of every month at 07:30 am
    - cron: '30 7 1 * *'
  workflow_dispatch: # Creates button on Github to trigger the workflow manually

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: Templates
    uses: amsterdam/github-workflows/.github/workflows/dependabot.yml@v1
    secrets: inherit  # Inherit secrets from the repository. You need to define "SLACK_TOKEN" in settings -> secrets -> actions!
    with:
      check_diff: false  # Create a list of major upgrades. Needs the Makefile target "diff"
      slack_channel: 'opdrachten-dependabot'  # Slack channel to post release steps to
      timetell_code: 240579  # Timetell project id
      acceptance_pipeline: "https://dev.azure.com/CloudCompetenceCenter/Opdrachten/_build?definitionId=4189"
      production_pipeline: "https://dev.azure.com/CloudCompetenceCenter/Opdrachten/_build?definitionId=4189"
      acceptance_urls: "https://acc.statistiekhub.amsterdam.nl/"
      production_urls: "https://statistiekhub.amsterdam.nl/"
